---
- name: check for updates
  hosts: localhost
  gather_facts: true

  tasks:
  - name: check for updates (yum)
    yum: list=updates update_cache=true
    register: yumoutput
    when: ansible_distribution == 'Red Hat Enterprise Linux'
  - debug: var=yumoutput
    msg: "{{ yumoutput.results | map(attribute='name') | list }}
