---
- name: check for updates
  hosts: all
  gather_facts: true

  tasks:
  - name: check for updates
    yum:
      list: updates
      update_cache: yes
    register: result
  - name: Show Output
    debug: var=yumoutput
      msg: "{{ yumoutput.results | map(attribute='name') | list }}"
