---
- hosts: all
  gather_facts: no

  tasks:

  - name: reboot host
    shell: sleep 10 && /sbin/shutdown -r now
    async: 300
    poll: 0
      
  - name: wait for rebooted hosts to return
    wait_for_connection:
      delay: 15
      timeout: 300

  - name: check uptime
    shell: uptime

