---
- hosts: all
  tasks:
  - name: Remove previously identified local accounts
    user:
      name: "{{ item }}"
      state: absent
    with_items: "{{ lookup('file', '/usr/local/bin/ansible/hosts/termination_march_2020').splitlines() }}"
    
