---
- hosts: all

  tasks:
  - name: "Copy login.defs file"
    copy:
      src: /usr/local/bin/ansible/roles/soxpasswd_files/login.defs
      dest: /etc/login.defs
      owner: root
      group: root
      mode: 0644

  - name: "Copy pam_pwquality.so file"
    copy:
      src: /usr/local/bin/ansible/roles/soxpasswd_files/pam_pwquality.so
      dest: /lib64/security/pam_pwquality.so
      owner: root
      group: root
      mode: 0644

  - name: "Copy system-auth-ac file for RHEL6"
    copy:
      src: /usr/local/bin/ansible/roles/soxpasswd_files/system-auth-ac  
      dest: /etc/pam.d/system-auth-ac 
      owner: root
      group: root
      mode: 0644
    when:
      - ansible_distribution_major_version == "6"

  - name: "Copy sysctl.conf file for RHEL6"
    copy:
      src: /usr/local/bin/ansible/roles/soxpasswd_files/rhel6_sysctl.conf
      dest: /etc/sysctl.conf
      owner: root
      group: root
      mode: 0644
    when:
      - ansible_distribution_major_version == "6"
    notify:
    - sysctl

  - name: "Copy system-auth-ac file for RHEL7"
    copy:
      src: /usr/local/bin/ansible/roles/soxpasswd_files/system-auth-ac_rhel7  
      dest: /etc/pam.d/system-auth-ac 
      owner: root
      group: root
      mode: 0644
    when:
      - ansible_distribution_major_version == "7"

  - name: "Copy password-auth-ac file for RHEL7"
    copy:
      src: /usr/local/bin/ansible/roles/soxpasswd_files/system-auth-ac_rhel7
      dest: /etc/pam.d/password-auth-ac
      owner: root
      group: root
      mode: 0644
    when:
      - ansible_distribution_major_version == "7"


  - name: "Copy sysctl.conf file for RHEL7"
    copy:
      src: /usr/local/bin/ansible/roles/soxpasswd_files/rhel7_sysctl.conf     
      dest: /etc/sysctl.conf
      owner: root
      group: root
      mode: 0644
    when:
      - ansible_distribution_major_version == "7"
    notify:
    - sysctl

  - name: "Copy pwquality.conf file for RHEL7"
    copy:
      src: /usr/local/bin/ansible/roles/soxpasswd_files/pwquality_rhel7     
      dest: /etc/security/pwquality.conf
      owner: root
      group: root
      mode: 0644
    when:
      - ansible_distribution_major_version == "7"
    notify:
    - sysctl

  - name: "Removing the /root/.rhosts file"
    file:
      path: /root/.rhosts
      state: absent

  handlers:
    - name: sysctl  
      command: /sbin/sysctl -p


