---
- hosts: all

  tasks:
  - name: upgrade all packages
    yum:
      name: '*'
      disablerepo: "*"
      enablerepo: "rhel-*"
      state: latest
      skip_broken: no
      exclude: jenkins*

  - name: reboot host
    shell: sleep 10 && /sbin/shutdown -r now
    async: 300
    poll: 0
      
  - name: wait for rebooted hosts to return
    wait_for_connection:
      delay: 15
      timeout: 300

  - name: check uptime
    shell: uptime
